### ISSUE TITLE
如何保存训练过程中的结果？

### ISSUE THREAD

**Issue by yyr6661** [luanshiyinyang/Tutorial#1]
![image](https://user-images.githubusercontent.com/55223374/67063826-bd052780-f19a-11e9-89b7-95833207e0ac.png)
每一轮迭代的所有指标，除了打印出来，请问要如何进行保存呢，或者在训练结束后如何提取呢

**Comment by luanshiyinyang** [comment]
可以使用pickle进行对象序列化
